name: CI
on: ['pull_request']

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        go: ["stable", "oldstable"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -vet all ./...
    - name: TestPureGo
      run: go test -v -vet all -tags purego ./...
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: '2023.1.2'
        install-go: false
        cache-key: ${{ matrix.go }}
